FROM node:latest

WORKDIR /usr/src/app

# Copy the package.json file to the working directory
COPY package.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Start the application
CMD ["npm", "start"]